version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.2
      - php7.4

  php8.2:
    build:
      context: ./docker/php8.2
    volumes:
      - ./src:/var/www/html
    container_name: php8.2_cli

  php7.4:
    build:
      context: ./docker/php7.4
    volumes:
      - ./src:/var/www/html
    container_name: php7.4_cli
